/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author OS10
 */
public class FrameMain extends javax.swing.JFrame {

    

    public FrameMain() {
        initComponents();
        ChildAdmin ca = new ChildAdmin(this);
        ca.setSize(pnMain.getWidth(), pnMain.getHeight());
        pnMain.add(ca);
        pnMain.updateUI();
//        LoginPanel lg =  new LoginPanel();
//        JPanel jPanel1 = new JPanel();
//        jPanel1.add(lg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        bntHome = new javax.swing.JButton();
        bntLogin = new javax.swing.JButton();
        bntInfo = new javax.swing.JButton();
        txtOrder = new javax.swing.JButton();
        bntReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        bntHome.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        bntHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-home-red-30.png"))); // NOI18N
        bntHome.setText("Home");
        bntHome.setMinimumSize(new java.awt.Dimension(150, 39));
        bntHome.setPreferredSize(new java.awt.Dimension(120, 39));
        bntHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntHomeActionPerformed(evt);
            }
        });

        bntLogin.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        bntLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-customer-red-30.png"))); // NOI18N
        bntLogin.setText("Login");
        bntLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLoginActionPerformed(evt);
            }
        });

        bntInfo.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        bntInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-home-red-30.png"))); // NOI18N
        bntInfo.setText("info");
        bntInfo.setMinimumSize(new java.awt.Dimension(150, 39));
        bntInfo.setPreferredSize(new java.awt.Dimension(120, 39));
        bntInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInfoActionPerformed(evt);
            }
        });

        txtOrder.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-home-red-30.png"))); // NOI18N
        txtOrder.setText("Order");
        txtOrder.setMinimumSize(new java.awt.Dimension(150, 39));
        txtOrder.setPreferredSize(new java.awt.Dimension(120, 39));
        txtOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderActionPerformed(evt);
            }
        });

        bntReport.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        bntReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-home-red-30.png"))); // NOI18N
        bntReport.setText("Report");
        bntReport.setMinimumSize(new java.awt.Dimension(150, 39));
        bntReport.setPreferredSize(new java.awt.Dimension(120, 39));
        bntReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bntHome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntReport, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bntLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntHome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntReport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLoginActionPerformed

    }//GEN-LAST:event_bntLoginActionPerformed

    private void bntHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntHomeActionPerformed
        pnMain.removeAll();
        ChildAdmin ca = new ChildAdmin(this);
        ca.setSize(pnMain.getWidth(), pnMain.getHeight());
        pnMain.add(ca);
        pnMain.updateUI();
    }//GEN-LAST:event_bntHomeActionPerformed

    private void bntInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntInfoActionPerformed

    private void txtOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderActionPerformed

    private void bntReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    public void setPanel(JPanel panel) {
        panel.setSize(pnMain.getWidth(), pnMain.getHeight());
        // panel.setVisible(true);
        pnMain.removeAll();
        pnMain.add(panel);
        pnMain.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntHome;
    private javax.swing.JButton bntInfo;
    private javax.swing.JButton bntLogin;
    private javax.swing.JButton bntReport;
    private javax.swing.JPanel pnMain;
    private javax.swing.JButton txtOrder;
    // End of variables declaration//GEN-END:variables
}
