/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import controlpack.ActBean;
import controlpack.GroupsBean;
import java.awt.Font;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author K
 */
public class SystemPn extends javax.swing.JPanel {

    GroupsBean gb = new GroupsBean();
    ActBean acb = new ActBean();

    /**
     * Creates new form SystemPn
     */
    public SystemPn() {
        initComponents();
        tbAct.getTableHeader().setFont(new Font("Trebuchet MS", Font.BOLD, 14));
        tbGroups.getTableHeader().setFont(new Font("Trebuchet MS", Font.BOLD, 14));
        hiddenGroup();
        hiddenAct();
        loadAct();
        loadGroup();
    }

    SystemPn(FrameMain aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void hiddenAct() {
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel5.setVisible(false);
        txtUpdateA.setVisible(false);
        jLabel6.setVisible(false);
        txtChargesA.setVisible(false);
        btnSubmitA1.setVisible(false);
    }

    public void btnToUpdateA() {
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel5.setVisible(true);
        txtUpdateA.setVisible(true);
        jLabel6.setVisible(true);
        txtChargesA.setVisible(true);
        btnSubmitA1.setVisible(true);
    }

    public void btnToCreateA() {
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel5.setVisible(true);
        txtUpdateA.setVisible(true);
        jLabel6.setVisible(true);
        txtChargesA.setVisible(true);
        btnSubmitA1.setVisible(true);
    }

    public void hiddenGroup() {
        jLabel4.setVisible(false);
        jLabel2.setVisible(false);
        txtCharges.setVisible(false);
        btnSubmitG.setVisible(false);
    }

    public void btnToUpdateG() {
        jLabel4.setVisible(true);
        jLabel2.setVisible(true);
        txtCharges.setVisible(true);
        btnSubmitG.setVisible(true);
    }

    public void loadAct() {
        DefaultTableModel model = (DefaultTableModel) tbAct.getModel();
        model.setRowCount(0);
        Vector<ActBean> item = acb.displayAll();
        Vector v;
        for (int i = 0; i < item.size(); i++) {
            v = new Vector();
            ActBean temp = item.get(i);
            int id = temp.act_id;
            String act = temp.act_type;
            float acharges = temp.charges;
            v.add(id);
            v.add(act);
            v.add(acharges);
            model.addRow(v);
        }
    }

    public void loadGroup() {
        DefaultTableModel model = (DefaultTableModel) tbGroups.getModel();
        model.setRowCount(0);
        Vector<GroupsBean> item = gb.loadAll();
        Vector v;
        for (int i = 0; i < item.size(); i++) {
            v = new Vector();
            GroupsBean temp = item.get(i);
            int id = temp.id;
            int fromO = temp.fromOld;
            String newStr = "";
            if (fromO == 0) {
                newStr = "New born";
            } else {
                newStr = fromO + " years old";
            }
            float charges = temp.charges;
            v.add(id);
            v.add(newStr);
            v.add(charges);
            model.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGroups = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSubmitG = new javax.swing.JButton();
        txtCharges = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panel11 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAct = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtUpdateA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtChargesA = new javax.swing.JTextField();
        btnSubmitA1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTabbedPane2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        tbGroups.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Group ID", "Group Age", "Charges"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGroups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGroupsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGroups);
        if (tbGroups.getColumnModel().getColumnCount() > 0) {
            tbGroups.getColumnModel().getColumn(0).setResizable(false);
            tbGroups.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbGroups.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbGroups.getColumnModel().getColumn(2).setResizable(false);
            tbGroups.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Charges:");

        btnSubmitG.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnSubmitG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImages/icons8-approval-30.png"))); // NOI18N
        btnSubmitG.setText("Submit");
        btnSubmitG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitGActionPerformed(evt);
            }
        });

        txtCharges.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Update");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmitG)
                            .addComponent(txtCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmitG)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Groups", panel1);

        tbAct.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tbAct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Activity", "Charges"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbActMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAct);
        if (tbAct.getColumnModel().getColumnCount() > 0) {
            tbAct.getColumnModel().getColumn(0).setResizable(false);
            tbAct.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbAct.getColumnModel().getColumn(1).setResizable(false);
            tbAct.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImages/icons8-add-new-30-or.png"))); // NOI18N
        jButton1.setText("New Activity");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Activity Name:");

        txtUpdateA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Charges:");

        txtChargesA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        btnSubmitA1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnSubmitA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImages/icons8-approval-30.png"))); // NOI18N
        btnSubmitA1.setText("Submit");
        btnSubmitA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitA1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("ID:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout panel11Layout = new javax.swing.GroupLayout(panel11);
        panel11.setLayout(panel11Layout);
        panel11Layout.setHorizontalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(panel11Layout.createSequentialGroup()
                        .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmitA1)
                            .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtChargesA)
                                .addComponent(txtUpdateA, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panel11Layout.setVerticalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel11Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(25, 25, 25)
                        .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUpdateA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChargesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmitA1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Activities of Nanny", panel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbGroupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGroupsMouseClicked
        DefaultTableModel tbModel = (DefaultTableModel) tbGroups.getModel();
        int currentRow = tbGroups.getSelectedRow();
        jLabel4.setVisible(true);
        txtCharges.setText(tbModel.getValueAt(currentRow, 2).toString());
        int id = (int) tbModel.getValueAt(currentRow, 0);
        btnToUpdateG();
    }//GEN-LAST:event_tbGroupsMouseClicked

    private void btnSubmitGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitGActionPerformed
        try {
            float charges = Float.valueOf(txtCharges.getText());
            System.out.println("Để update");
            DefaultTableModel tbModel = (DefaultTableModel) tbGroups.getModel();
            int currentRow = tbGroups.getSelectedRow();
            int id = Integer.valueOf(tbModel.getValueAt(currentRow, 0).toString());
            if (gb.updateGroup(id, charges)) {
                JOptionPane.showMessageDialog(this, "Update successful!!");
                hiddenGroup();
                loadGroup();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Charges must be a number!!");
        }
    }//GEN-LAST:event_btnSubmitGActionPerformed

    private void btnSubmitA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitA1ActionPerformed
        if (!jLabel7.isVisible()) {
            float charges = Float.valueOf(txtChargesA.getText());
            String str = txtUpdateA.getText();
            if (acb.createGroup(str, charges)) {
                hiddenAct();
                loadAct();
            } else {
                JOptionPane.showMessageDialog(this, "Activity is exist!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            DefaultTableModel tbModel = (DefaultTableModel) tbAct.getModel();
            int currentRow = tbAct.getSelectedRow();
            int id = (int) tbModel.getValueAt(currentRow, 0);
            float charges = Float.valueOf(txtChargesA.getText());
            if (acb.updateGroup(id, txtUpdateA.getText(), charges)) {
                hiddenAct();
                loadAct();
            } else {
                JOptionPane.showMessageDialog(this, "Activity is exist!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSubmitA1ActionPerformed

    private void tbActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbActMouseClicked
        DefaultTableModel tbModel = (DefaultTableModel) tbAct.getModel();
        int currentRow = tbAct.getSelectedRow();
        jLabel8.setText(tbModel.getValueAt(currentRow, 0).toString());
        txtUpdateA.setText(tbModel.getValueAt(currentRow, 1).toString());
        txtChargesA.setText(tbModel.getValueAt(currentRow, 2).toString());
        btnToUpdateA();
    }//GEN-LAST:event_tbActMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtUpdateA.setText("");
        txtChargesA.setText("");
        btnToCreateA();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitA1;
    private javax.swing.JButton btnSubmitG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel11;
    private javax.swing.JTable tbAct;
    private javax.swing.JTable tbGroups;
    private javax.swing.JTextField txtCharges;
    private javax.swing.JTextField txtChargesA;
    private javax.swing.JTextField txtUpdateA;
    // End of variables declaration//GEN-END:variables
}
